baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "pxcan.js Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
# publish to GitHub Pages folder: /docs
publishDir = "../docs"

[params]
	# General information
	author = "shamblesides"
	description = "Pixels on an HTML5 Canvas, done right."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/shamblesides/pxcan"

	version = "0.1"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "light red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "shamblesides"
	github  = "shamblesides"


[[menu.main]]
	name   = "pxcan.js"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Examples"
	url    = "examples/"
	weight = 10

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= false
	fractions = true
	smartDashes = true
	plainIDAnchors = true